### ISSUE TITLE
Flaky test failure

### ISSUE THREAD

**Issue by olavloite** [googleapis/dotnet-spanner-nhibernate#76]
```
[xUnit.net 00:00:02.32]     Google.Cloud.Spanner.Connection.MockServer.MockSpannerServerTests.WriteMutations [FAIL]
[xUnit.net 00:00:02.32]       System.InvalidCastException : Unable to cast object of type 'Google.Cloud.Spanner.V1.BeginTransactionRequest' to type 'Google.Cloud.Spanner.V1.CommitRequest'.
[xUnit.net 00:00:02.32]       Stack Trace:
[xUnit.net 00:00:02.32]         D:\a\dotnet-spanner-nhibernate\dotnet-spanner-nhibernate\Google.Cloud.Spanner.Connection.Tests\MockServer\MockSpannerServerTests.cs(104,0): at Google.Cloud.Spanner.Connection.MockServer.MockSpannerServerTests.WriteMutations()
[xUnit.net 00:00:02.32]         --- End of stack trace from previous location where exception was thrown ---
  X Google.Cloud.Spanner.Connection.MockServer.MockSpannerServerTests.WriteMutations [67ms]
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'Google.Cloud.Spanner.V1.BeginTransactionRequest' to type 'Google.Cloud.Spanner.V1.CommitRequest'.
  Stack Trace:
     at Google.Cloud.Spanner.Connection.MockServer.MockSpannerServerTests.WriteMutations() in D:\a\dotnet-spanner-nhibernate\dotnet-spanner-nhibernate\Google.Cloud.Spanner.Connection.Tests\MockServer\MockSpannerServerTests.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by olavloite** [comment]
Closing as it has not happened since
